### PR TITLE
Update testing, clarify name, fix testing when bzr is not available

### PR DESCRIPTION
**Pull request by jeffbyrnes**
A good amount of changes here. To summarize:

* Update default to Golang 1.14.4
    - This may be breaking, but only if Google is not obeying SemVer for Go
* Update the testing to run against current OS versions & use current tooling
* Switch to GitHub Actions for testing automation
* Update some URLs/locations
* Add ability to handle cases where `bzr` is not an available package (e.g., CentOS 8)
* Drop support for Chef 12 & 13 (they are >2 years EOL)
* Flip back to consistently using the `golang` name for the cookbook
    - It has remained `golang` on Supermarket, so may as well

The commits should accurately express everything else, but those are the highlights.

### CODE REVIEW

**Comment by mburns** [comment]
Hi @jeffbyrnes 

These changes look reasonable from a glance, and I'd be happy to help you land this. But please note that @NOX73 is the only user that can upload a new version to the Supermarket (see #68), and we are already *very* outdated.

It might make sense to fork, or locking your version to a git repo/branch in your Berksfile.

**Comment by NOX73** [comment]
Is it still alive?

Not sure I can handle this, it's about 5 years I do not use chef.

**Comment by jeffbyrnes** [comment]
@NOX73 that’s ok!

I’m happy to take over.

If that works for you, would you:

* Make me the owner of https://supermarket.chef.io/cookbooks/golang
* Either making me an admin-level contributor, or make me the owner, of this repo

**Comment by jeffbyrnes** [comment]
Realized Travis CI just wasn't having any of this, so I went ahead & did some GitHub Actions magic instead.

Works well on my fork, though the source recipe is a bit busted. I’ll clean that up in a future branch, however; this one is big enough.

**Comment by NOX73** [comment]
There is one thing. I see some cookbooks have a dependency on it. So it would be a security issue if I just put it to the stranger's hands, right? How we can manage this?

**Comment by NOX73** [comment]
Is there someone who I can verify somehow and transfer ownership to?

**Comment by jeffbyrnes** [comment]
@NOX73 understandable! Perhaps I can offer my ownership of other community cookbooks as bona fides?

I maintain:

* [zookeeper](https://supermarket.chef.io/cookbooks/zookeeper)
* [myql_logrotate](https://supermarket.chef.io/cookbooks/mysql_logrotate)
* [opencv](https://supermarket.chef.io/cookbooks/opencv)
* [archiva](https://supermarket.chef.io/cookbooks/archiva)
* [lockrun](https://supermarket.chef.io/cookbooks/lockrun)
* [storage](https://supermarket.chef.io/cookbooks/storage)

**Comment by jeffbyrnes** [comment]
I’m also a [member of sous-chefs](https://github.com/orgs/sous-chefs/people?query=jeff)

**Comment by mburns** [comment]
+1 to https://github.com/sous-chefs , that seems like an ideal place.

I don't use Chef much anymore at my day job, but I'm happy to help. https://supermarket.chef.io/users/burnsie

**Comment by jeffbyrnes** [comment]
Indeed, I’m happy to help shepherd it to ownership by @sous-chefs.

**Comment by NOX73** [comment]
https://supermarket.chef.io/cookbooks/consul#dependencies
@jeffbyrnes this is yours, right? I've found this keeps dependency on golang

I can't believe it's possible to run the same code for 5 years )))

**Comment by jeffbyrnes** [comment]
That’s one of sous-chef’s cookbooks, yep! I’ve got a single commit of mine in there (just docs, but hey, it’s a real commit 😁)

And yeah, this Go cookbook has had some long legs, heh.

**Comment by NOX73** [comment]
OK, I think it's pretty clear. I can transfer it. @jeffbyrnes Do you need supermarket ownership only? What's your plan on this repo? Will you fork it?

**Comment by NOX73** [comment]
I will transfer it ot @sous-chefs on supermarket, is it ok?

**Comment by jeffbyrnes** [comment]
I’d suggest:

* transfer Supermarket ownership to @sous-chefs
* transfer this repo ownership to @sous-chefs

I’ll reach out to some of the other folks to help get it settled in its new home :)

Thanks @NOX73!

**Comment by jeffbyrnes** [comment]
Ah, just re-read the docs, and you have to me a member to transfer it in. You are welcome to transfer it to me, and I’ll then transfer it to @sous-chefs.

**Comment by NOX73** [comment]
> jeffbyrnes/chef-golang already exists
%)

**Comment by jeffbyrnes** [comment]
Stand by!

**Comment by jeffbyrnes** [comment]
Ok all set, please try again :)

**Comment by NOX73** [comment]
it's requested

**Comment by jeffbyrnes** [comment]
And we’re all set! Thanks so much for creating the cookbook @NOX73, it’ll have an excellent home with @sous-chefs.

**Comment by jeffbyrnes** [comment]
@NOX73 when you can, would you also transfer Supermarket ownership if you haven’t already? I’ll reach out the @sous-chefs/board and ask them to accept & then we can publish a new version.

**Comment by Xorima** [comment]
I can confirm sous now have the cookbook, I haven't checked supermarket yet though so if someone can ensure that is transferred to sous chefs as well (add yourself as a collaborator if you want to) that would be great

**Comment by jeffbyrnes** [comment]
@Xorima thanks! I figured sous would be a good home for this cookbook, instead of just me.

**Comment by jeffbyrnes** [comment]
@Xorima that’s pretty slick.

We should probably publish the existing tags that are not on Supermarket, as a start.

What _is_ the sous publish method, anyway? I’m still pretty new to the group.

**Pull request merged**
